char ways[100][50] = {"Keep a tidy house for them",
                 "Be sure to clip their claws",
                 "Scoop their box daily",
                 "Brush them with a hair brush",
                 "Don't squeeze their paws hard",
                 "Give them some fresh water",
                 "Let them have a fish",
                 "Buy them a scratching post",
                 "Put them in your lap",
                 "Be quiet when they're sleeping",
                 "Whisper I love you",
                 "Rub their soft belly",
                 "Make sure their tail is clean",
                 "Give them a yarn ball",
                 "Make them a nice bed",
                 "Buy them some catnip",
                 "Play them some music",
                 "Give them a cute collar",
                 "Make sure their vaccinated",
                 "Take their picture",
                 "Brush their teeth",
                 "Let them watch T.V.",
                 "Don't let them be outside by themselves",
                 "Feed them some cat food",
                 "Make sure their eyes are clean",
                 "Put a liner in their box",
                 "Give them a mat to wipe their feet on",
                 "Don't forget them on Christmas",
                 "Make sure their spay or neutered",
                 "Hold them like a baby",
                 "Let them have a towel or blanket",
                 "Keep your toilet lid down",
                 "Don't let them chew on power cords",
                 "Set them by the window",
                 "Cat proof your home",
                 "Change their litter weekly",
                 "Praise them lavishly",
                 "Never feed them chicken bones",
                 "Teach them a funny trick",
                 "Give them a toy mouse",
                 "Clean up their hairballs",
                 "Keep them away from candles",
                 "Give them a separate zone",
                 "Never play with them aggressively",
                 "Increase his cuddle time",
                 "Be sure to watch his weight",
                 "If you leave turn on the radio",
                 "Scold him firmly but with kindness",
                 "Respond when he meows",
                 "Give them a thing of cat grass",
                 "Scratch under his chin",
                 "Remind him that you love him",
                 "Give them a box to play in",
                 "If they're old help them get down",
                 "Let them lick you with their rough tongue",
                 "Record precious memories",
                 "Dress them up in ribbons",
                 "Give them a flea treatment",
                 "Make a vet appointment",
                 "Give them a little wet food",
                 "When they scratch you don't get angry",
                 "Give them some private time",
                 "Treat them with respect",
                 "When he grooms himself say good job",
                 "Let them chase a laser pointer",
                 "Clean out their ears",
                 "Never smoke around them",
                 "Buy a sturdy cat carrier",
                 "Listen to them purr",
                 "Something by temptations",
                 "Give them your full attention",
                 "Don't trap them in the laundry basket",
                 "Let them sleep in bed with you",
                 "Make sure they're not locked in the closet",
                 "Don't let them play in plastic bags",
                 "Give them a massage",
                 "Touch him as you pass by",
                 "If he's on the couch don't be mad",
                 "If they hate fans turn the fan off",
                 "When there's a bird outside say hey look",
                 "Intrigue them with a funny sound",
                 "Don't forget sardine time",
                 "Let him play with your old socks",
                 "Stroke him the direction that his fur goes",
                 "Admire his long whiskers",
                 "Keep his box away from his food",
                 "Pretend that he's a piano",
                 "Don't interrupt them while they're eating",
                 "When they're scared go and comfort them",
                 "Let him have a lick",
                 "If their breath stinks give them Greenies",
                 "Give him a ball with a bell in it",
                 "If it's hot put ice in their bowl",
                 "Let him drink out of the sink",
                 "Don't vacuum if it scares him",
                 "Draw a picture of him",
                 "If you drop some food it's theirs now",
                 "Read him a book",
                 "Feed him again",
                 "Just love him every day"};
unsigned int ways_offset[100] = {
1205,
3962,
6546,
9302,
14814,
17398,
20155,
22739,
28423,
31007,
33764,
36348,
42032,
44616,
47373,
49957,
55641,
58225,
60809,
63566,
69767,
72351,
75107,
77691,
83376,
85960,
88544,
91300,
96813,
99569,
102153,
104737,
110422,
113006,
115590,
118346,
124031,
126615,
129371,
131955,
137640,
140224,
142808,
145392,
151076,
153833,
156417,
159173,
164685,
167442,
170026,
172610,
178122,
180878,
183462,
186219
};
